### ISSUE TITLE
User Monitoring

### ISSUE THREAD

**Issue by jtchilders** [PanDAWMS/panda-harvester#31]
Hi Tadashi,

As I run Harvester, I'm finding it difficult to peruse 10-15 log files each running concurrently and trying to stitch together a picture of Harvester's current state. 

Could we have a few monitoring scripts which can be run from the command line by the user that reports on each worker that is running. In the case of ManyToOne running you might present the state of each worker and a summary of the panda job states, i.e. N-panda jobs are in 'prepare', M-panda jobs are in 'fetch', etc.

This would be really useful.

Another option that would be useful to see is the ability to put an email or list of emails in the harvester config to which error messages could be sent. That way operation teams can know without looking at the logs when errors occur.

Thanks,
Taylor

**Comment by tmaeno** [comment]
Hi Taylor,

Harvester uploads job and worker information to the central Oracle database from local sqlite/mariaDB, so that it is possible to have monitoring pages for each harvester instance in bigpandamon. Actually I submitted a jira ticket for a summary page

https://its.cern.ch/jira/browse/ATLASPANDA-395

If you need other pages like mapping between jobs and workers, it is better to submit jira tickets. 

Concerning alarm, it is possible to feed the information from Oracle to kibana. I suppose that there is a standard alarm mechanism based on kibana, so we don't need to invent a new mechanism.
